### ISSUE TITLE
Error in flow and SSR setup

### ISSUE THREAD

**Issue by Thomas-X** [oberonamsterdam/create-react-stack#16] opened 2017-11-13 13:12 UTC
![screen shot 2017-11-13 at 14 11 01](https://user-images.githubusercontent.com/21952645/32727377-9ee006b0-c87c-11e7-8961-aa9766d86948.png)

**Comment by jariz** [comment] 2017-11-27 12:57
Duplicate of #17

**Closed as completed by jariz** 2017-11-27 12:57 UTC
Labels: duplicate
